{{- if and .Values.persistence.enabled (not .Values.persistence.web.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-web" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.persistence.web.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.persistence.web.annotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.web.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.web.size | quote }}
  {{- if .Values.persistence.web.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.web.selector "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.persistence.web.dataSource }}
  dataSource: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.web.dataSource "context" $) | nindent 4 }}
  {{- end }}
  {{- include "common.storage.class" (dict "persistence" .Values.persistence.web "global" .Values.global) | nindent 2 }}
{{- end -}}
