apiVersion: v2
name: vyhub
type: application
version: 1.0.0
dependencies:
  - name: common
    version: ^2.23.0
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: loki
    version: ^6.16.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
