{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vyhub.postgresql.name" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  {{- $passKey := .Values.postgresql.auth.secretKeys.userPasswordKey }}
  {{- $pass := required "postgresql.auth.password must be set when postgresql.enabled is true and no existingSecret is provided" .Values.postgresql.auth.password }}
  {{ $passKey }}: {{ $pass | b64enc | quote }}
{{- end }}
