#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER "$POSTGRES_VYHUB_USER" PASSWORD '$POSTGRES_VYHUB_PASSWORD';
	ALTER DATABASE "$POSTGRES_DB" OWNER TO "$POSTGRES_VYHUB_USER";
EOSQL