variable "hcloud_token" {
  description = "Hetzner Cloud API token (read+write)."
  type        = string
  sensitive   = true
}

variable "server_name" {
  description = "Name of the Hetzner Cloud server."
  type        = string
  default     = "vyhub-onprem"
}

variable "location" {
  description = "Hetzner Cloud location (e.g. nbg1, fsn1, hel1, ash, hil, sin)."
  type        = string
  default     = "nbg1"
}

variable "server_type" {
  description = "Hetzner Cloud server type (e.g. cax11, cax21, cpx11, cx22)."
  type        = string
  default     = "cax11"
}

variable "image" {
  description = "OS image used for the server."
  type        = string
  default     = "debian-13"
}

variable "ssh_public_keys" {
  description = "List of SSH public keys (full key strings) authorized for root access."
  type        = list(string)
  validation {
    condition     = length(var.ssh_public_keys) > 0
    error_message = "At least one SSH public key must be provided."
  }
}

variable "coolify_admin_email" {
  description = "Email address for the Coolify root admin user; also used for Let's Encrypt expiry notices."
  type        = string
}

variable "coolify_admin_password" {
  description = "Password for the Coolify root admin user. Auto-generated by setup.sh."
  type        = string
  sensitive   = true
}

variable "vyhub_fqdn" {
  description = "FQDN at which VyHub will be served via HTTPS (e.g. vyhub.example.com). Coolify's admin UI is only reachable via SSH tunnel (port 8000); it is not exposed publicly."
  type        = string
}

variable "vyhub_env" {
  description = "Map of VYHUB_* env vars pushed into the Coolify Docker Compose resource for VyHub."
  type        = map(string)
  sensitive   = true
  default     = {}
}

variable "registry_url" {
  description = "Container registry URL Coolify should authenticate against before pulling images (e.g. registry.matbyte.com)."
  type        = string
  default     = ""
}

variable "registry_user" {
  description = "Username for the container registry."
  type        = string
  sensitive   = true
  default     = ""
}

variable "registry_password" {
  description = "Password / token for the container registry."
  type        = string
  sensitive   = true
  default     = ""
}

variable "compose_url" {
  description = "Raw URL of docker-compose.coolify.yml fetched by cloud-init when bootstrapping the Coolify resource via API."
  type        = string
  default     = "https://raw.githubusercontent.com/matbyte-com/vyhub-onprem/setup/docker-compose.coolify.yml"
}

variable "enable_backups" {
  description = "Enable Hetzner Cloud backups for the server (+20% cost)."
  type        = bool
  default     = false
}

variable "labels" {
  description = "Labels applied to created Hetzner resources."
  type        = map(string)
  default = {
    managed-by = "vyhub-onprem-setup"
  }
}
