apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "vyhub.geoipApi.name" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: geoip-api
  {{- if or .Values.geoipApi.deploymentAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.geoipApi.deploymentAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.geoipApi.autoscaling.hpa.enabled }}
  replicas: {{ .Values.geoipApi.replicaCount }}
  {{- end }}
  {{- if .Values.geoipApi.updateStrategy }}
  strategy: {{- toYaml .Values.geoipApi.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.geoipApi.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: geoip-api
  template:
    metadata:
      {{- if .Values.geoipApi.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.geoipApi.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: geoip-api
    spec:
      {{- include "vyhub.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ template "vyhub.geoipApi.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.geoipApi.automountServiceAccountToken }}
      {{- if .Values.geoipApi.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.geoipApi.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.geoipApi.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.geoipApi.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.geoipApi.podAffinityPreset "component" "geoipApi" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.geoipApi.podAntiAffinityPreset "component" "geoipApi" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.geoipApi.nodeAffinityPreset.type "key" .Values.geoipApi.nodeAffinityPreset.key "values" .Values.geoipApi.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.geoipApi.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.geoipApi.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.geoipApi.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.geoipApi.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.geoipApi.priorityClassName }}
      priorityClassName: {{ .Values.geoipApi.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.geoipApi.schedulerName }}
      schedulerName: {{ .Values.geoipApi.schedulerName | quote }}
      {{- end }}
      {{- if .Values.geoipApi.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.geoipApi.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.geoipApi.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.geoipApi.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.geoipApi.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.geoipApi.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        {{- if and .Values.volumePermissions.enabled .Values.persistence.enabled }}
        - name: volume-permissions
          image: {{ include "geoipApi.volumePermissions.image" . }}
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy | quote }}
          command:
            - /bin/bash
            - -ec
          {{- if .Values.volumePermissions.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.volumePermissions.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- else if ne .Values.volumePermissions.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.volumePermissions.resourcesPreset) | nindent 12 }}
          {{- end }}
          volumeMounts: []
        {{- end }}
        {{- if .Values.geoipApi.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.geoipApi.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: geoip-api
          image: {{ template "vyhub.geoipApi.image" . }}
          imagePullPolicy: {{ .Values.geoipApi.image.pullPolicy }}
          {{- if .Values.geoipApi.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.geoipApi.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.geoipApi.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.geoipApi.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.geoipApi.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.geoipApi.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.geoipApi.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.geoipApi.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.geoipApi.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.geoipApi.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.geoipApi.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.geoipApi.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.geoipApi.resources }}
          resources: {{- toYaml .Values.geoipApi.resources | nindent 12 }}
          {{- else if ne .Values.geoipApi.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.geoipApi.resourcesPreset) | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.geoipApi.containerPorts.http }}
            {{- if .Values.geoipApi.extraContainerPorts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.geoipApi.extraContainerPorts "context" $) | nindent 12 }}
            {{- end }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.geoipApi.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.geoipApi.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.geoipApi.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.geoipApi.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /actuator/health
              port: {{ .Values.geoipApi.containerPorts.http }}
              scheme: HTTP
          {{- end }}
          {{- if .Values.geoipApi.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.geoipApi.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.geoipApi.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.geoipApi.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /actuator/health
              port: {{ .Values.geoipApi.containerPorts.http }}
              scheme: HTTP
          {{- end }}
          {{- if .Values.geoipApi.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.geoipApi.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.geoipApi.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.geoipApi.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /actuator/health
              port: {{ .Values.geoipApi.containerPorts.http }}
              scheme: HTTP
          {{- end }}
          {{- end }}
          {{- if .Values.geoipApi.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.geoipApi.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
          {{- if .Values.geoipApi.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.geoipApi.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.geoipApi.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.geoipApi.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: empty-dir
          emptyDir: {}
        {{- if .Values.geoipApi.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.geoipApi.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
